### ISSUE TITLE
[Question] How to use specify a prerelease version as 1.0.0.build-1

### ISSUE THREAD

**Issue by xyloman** [concourse/semver-resource#68]
We are evaluating moving our builds from 1.0.0.beta-1 to 1.0.0.build-1 similar to how Pivotal is versioning the tiles that they release on pivnet.  We see a lot of benefits in this versioning scheme in that we would be able to build the artifact once (in this case a spring boot application) and promote it through the pipeline and not have to rebuild it when shiping it as a release. Instead we would move the preelease from the pre-release repository to the release repository and the binary will not change or the version.  Is this feasible with the semver-resource in concourse?  Is there a different resource that we might look at?  Is this the same resource that Pivotal release engineering uses for versioning their tiles?

**Comment by jama-pivotal** [comment]
If i'm understanding you correctly @xyloman , you're asking if you can simply change from using `beta` to `build` semantics in your `semver-resource`.  If you take a look at the Concourse CI pipelines you'll notice under our `version` we use `rc` prefix instead of `beta`:

https://ci.concourse-ci.org/teams/main/pipelines/main/resources/version  

and that's actually specified in our pipeline yml here: 

https://github.com/concourse/pipelines/blob/cab5e70fdc2d73ce71423212011f25a37db9d2b9/ci.concourse-ci.org/concourse.yml#L163-L172

I believe you can do something similar, as described https://github.com/concourse/semver-resource/#version-bumping-semantics

**Comment by aegershman** [comment]
I'm not sure if all these product teams at Pivotal are using Concourse to build/deliver products, though I've noticed a fair number of products which use the `*.build-x` notation. I'm presuming that they're using Concourse for building/delivering, and I'm presuming they're using some form of the `semver` resource to do it. I could be totally off on this though, I have no idea.

Just for reference, here's some pics of what I'm referring to:

![director](https://user-images.githubusercontent.com/5619476/44058948-660cfd78-9f15-11e8-8306-58feb681853f.png)

(Spring data flow is especially interesting since in it's download history there are `final` releases, `*.rc` releases, and `*.build` releases)

![flow](https://user-images.githubusercontent.com/5619476/44058949-661a95b4-9f15-11e8-89a2-99eadef58876.png)
![metrics](https://user-images.githubusercontent.com/5619476/44058950-66263112-9f15-11e8-9704-e9d31699ea55.png)
![pcloudcache](https://user-images.githubusercontent.com/5619476/44058951-66340b0c-9f15-11e8-8eb9-b791ccb13d9d.png)
![healthwatch](https://user-images.githubusercontent.com/5619476/44058952-6641a8d4-9f15-11e8-8187-f3dec03abb86.png)
![mysqlv2](https://user-images.githubusercontent.com/5619476/44058953-664f6c62-9f15-11e8-8b1b-49f50123ba20.png)

**Comment by xyloman** [comment]
@aegershman that is exactly what we are looking for.  What I envision is the ability to build for instance a spring boot application once say 1.0.2-build.25.  If that version passes through the test gate in our pipeline it would then be pushed to the ship it gate.  Instead of having to build the artifact again just to change the version I think it would be better to take the endstate that passed the test gate and move from the build maven repo to the released maven repo unmodified.  If for some reason it failed some quality assurance test it should go back through the build process where the build number would increment to .26 and so on and so forth.  What we do today is rebuild the end state during the ship phase which is unnecessary and only done to lop off the -build.25 portion of the build number.

**Comment by aegershman** [comment]
Whelp. Pretty sure all you have to do is specify `pre: build` in your `params:` block, like so:

```yml
jobs:
- name: build
  plan:
  - get: version
    params:
      pre: build # <--- other options are alpha, beta, rc, etc.
  - put: version
    params:
      file: version/version
```

**Comment by vito** [comment]
merged https://github.com/concourse/semver-resource/pull/78 - thanks @aegershman!
